##===- projects/sample/lib/Makefile ------------------------*- Makefile -*-===##

#
# Relative path to the top of the source tree.
#
LEVEL=..

#
# List all of the subdirectories that we will compile.
#

DIRS=\
Utilities\
Analysis\
Metadata\
CorelabHLS\
Transform\
HLSTest\
Exectime
#Metadata\
Utilities\
ICFG\
AliasAnalysis\
CAMP


include $(LEVEL)/Makefile.common
